language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t imimcolee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true imimcolee/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-072200021928"
  bucket_path: "docker-react"
  on:
    bracnk:  master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"